### ISSUE TITLE
Features on Rust homepage are unintelligible jargon

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-marketing#15]
Features listed on Rust’s homepage are implementation details, rather than benefits for the user.

Now that I know Rust I appreciate how useful these features are, but before using Rust I never thought I'd want a language with "move semantics" or "trait-based generics". In fact, such terms make it sound complicated and off-putting.

   * move semantics — to someone coming from C it is absolutely meaningless term, but "you can guarantee there's only one copy of a struct" or "you can enforce an object is not used after it's freed" is marvelous.
   * trait-based generics — I’ve first heard of "traits" in PHP, and generics in Java, and neither of these seemed interesting.
   * type inference —  doesn’t sound as great as “you get strict type-checking without having to write every type manually”
   * minimal runtime — could be “can be linked with C programs with no hassle” and “works on microcontrollers”

I appreciate it's very hard to replace that list, because it's impossible to explain these things in 3 words. For most of these features I had no idea I want them until I used them.

And it's missing some other features (some of which are not strictly language features, but make Rust great in practice):

 * error handling as convenient as exceptions, as predictable as error codes,
 * standard package manager that makes dependencies easy to use and reliable,
 * easy to use built-in unit testing,
 * clear and helpful error messages,
 * developed in the open, with cooperation with the community.

----

I think Elixir website presents the features well:

https://elixir-lang.org/

Each feature is a section with description and example code. It's easier to show e.g. pattern matching than to describe it.

**Comment by steveklabnik** [comment]
This is certainly something most people agree on.

**Comment by Moxinilian** [comment]
I support this deeply. It took me more than a year from seeing the main page to discovering what Rust really was about. Something really should be done about that!

**Comment by aturon** [comment]
Yep, the website is getting a complete overhaul as part of Rust 2018, and this issue will definitely be addressed there.

I'm going to close this issue though as it's out of scope for this repo.
